#!/bin/bash

mkdir -p home/{.config,.npm,composer,composer_cache}
chmod -R 777 home/{.config,.npm,composer,composer_cache}

mkdir -p services/{database,storage}/data
chmod -R 777 services/{database,storage}/data